### ISSUE TITLE
BDHero GUI v0.9.0.6: System.IndexOutOfRangeException: Indekset lå uden for arrayets grænser.

### ISSUE THREAD

**Issue by bdhero-issues** [bdhero/bdhero#27] opened 2014-04-14 09:35 UTC
BDHero GUI v0.9.0.6 (built on 2014-04-08 01:06:16Z)
## Stack Trace

```
System.IndexOutOfRangeException: Indekset lå uden for arrayets grænser.
   ved BDInfo.TSStreamFile.Scan(List`1 playlists, Boolean isFullScan)
   ved BDInfo.BDROM.Scan(CancellationToken cancellationToken)
   ved BDHero.Plugin.DiscReader.DiscReader.ScanBDROM(CancellationToken cancellationToken, String bdromPath)
   ved BDHero.Plugin.DiscReader.DiscReader.ReadBDROM(CancellationToken cancellationToken, String bdromPath)
   ved BDHero.Controller.<>c__DisplayClass29.<ReadBDROM>b__27(CancellationToken token)
   ved BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   ved DotNetUtils.Concurrency.Promise`1.Work()
   ved DotNetUtils.Concurrency.Promise`1.TryDoWork()

Source: BDInfo
```
## Log Events

```
2014-04-14 11:36:07,983 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:22 elapsed, 00:00:01 remaining
2014-04-14 11:36:08,232 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:22 elapsed, 00:00:01 remaining
2014-04-14 11:36:08,484 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:23 elapsed, 00:00:01 remaining
2014-04-14 11:36:08,745 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:23 elapsed, 00:00:01 remaining
2014-04-14 11:36:08,996 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:23 elapsed, 00:00:01 remaining
2014-04-14 11:36:09,249 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:23 elapsed, 00:00:01 remaining
2014-04-14 11:36:09,499 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:24 elapsed, 00:00:01 remaining
2014-04-14 11:36:09,751 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:24 elapsed, 00:00:01 remaining
2014-04-14 11:36:10,013 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:24 elapsed, 00:00:01 remaining
2014-04-14 11:36:10,264 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:24 elapsed, 00:00:01 remaining
2014-04-14 11:36:10,529 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:25 elapsed, 00:00:01 remaining
2014-04-14 11:36:10,777 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:25 elapsed, 00:00:01 remaining
2014-04-14 11:36:11,034 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:25 elapsed, 00:00:01 remaining
2014-04-14 11:36:11,280 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:26 elapsed, 00:00:01 remaining
2014-04-14 11:36:11,530 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:26 elapsed, 00:00:01 remaining
2014-04-14 11:36:11,781 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:26 elapsed, 00:00:01 remaining
2014-04-14 11:36:12,045 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:26 elapsed, 00:00:01 remaining
2014-04-14 11:36:12,309 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:27 elapsed, 00:00:01 remaining
2014-04-14 11:36:12,558 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:27 elapsed, 00:00:01 remaining
2014-04-14 11:36:12,816 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:27 elapsed, 00:00:01 remaining
2014-04-14 11:36:13,075 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:27 elapsed, 00:00:01 remaining
2014-04-14 11:36:13,332 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:28 elapsed, 00:00:01 remaining
2014-04-14 11:36:13,579 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:28 elapsed, 00:00:01 remaining
2014-04-14 11:36:13,843 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:28 elapsed, 00:00:01 remaining
2014-04-14 11:36:14,105 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:28 elapsed, 00:00:01 remaining
2014-04-14 11:36:14,362 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:29 elapsed, 00:00:01 remaining
2014-04-14 11:36:14,620 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:29 elapsed, 00:00:01 remaining
2014-04-14 11:36:14,872 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:29 elapsed, 00:00:01 remaining
2014-04-14 11:36:15,122 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:29 elapsed, 00:00:01 remaining
2014-04-14 11:36:15,373 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:30 elapsed, 00:00:01 remaining
2014-04-14 11:36:15,638 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:30 elapsed, 00:00:01 remaining
2014-04-14 11:36:15,889 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:30 elapsed, 00:00:01 remaining
2014-04-14 11:36:16,140 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:30 elapsed, 00:00:01 remaining
2014-04-14 11:36:16,404 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:31 elapsed, 00:00:01 remaining
2014-04-14 11:36:16,668 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:31 elapsed, 00:00:02 remaining
2014-04-14 11:36:16,930 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:31 elapsed, 00:00:02 remaining
2014-04-14 11:36:17,192 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:31 elapsed, 00:00:02 remaining
2014-04-14 11:36:17,456 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:32 elapsed, 00:00:02 remaining
2014-04-14 11:36:17,716 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:32 elapsed, 00:00:02 remaining
2014-04-14 11:36:17,980 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:32 elapsed, 00:00:02 remaining
2014-04-14 11:36:18,229 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:32 elapsed, 00:00:02 remaining
2014-04-14 11:36:18,485 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:33 elapsed, 00:00:02 remaining
2014-04-14 11:36:18,731 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:33 elapsed, 00:00:02 remaining
2014-04-14 11:36:18,998 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:33 elapsed, 00:00:02 remaining
2014-04-14 11:36:19,247 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:33 elapsed, 00:00:02 remaining
2014-04-14 11:36:19,521 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:34 elapsed, 00:00:02 remaining
2014-04-14 11:36:19,785 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:34 elapsed, 00:00:02 remaining
2014-04-14 11:36:20,013 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:34 elapsed, 00:00:02 remaining
2014-04-14 11:36:20,265 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Error - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:34 elapsed, 00:00:02 remaining
2014-04-14 11:36:20,271 [ 1] ERROR BDHero.Controller - Unhandled exception was thrown by plugin
```
## Plugins

| R/O | Plugin Name | Version | Build Date | E/D |
| --- | --- | --- | --- | --- |
| 0 | BDInfo Disc Reader | 0.5.8.2 | 2014-04-08 01:06:11Z |  |
| 0 | ISAN Metadata Provider | 0.9.0.6 | 2014-04-08 01:06:11Z |  |
| 1 | TMDb | 0.9.0.6 | 2014-04-08 01:06:11Z |  |
| 2 | ChapterDb | 0.9.0.6 | 2014-04-08 01:06:11Z |  |
| 0 | BDHero Detective | 0.9.0.6 | 2014-04-08 01:06:11Z |  |
| 0 | BDHero File Namer | 0.9.0.6 | 2014-04-08 01:06:12Z |  |
| 0 | FFmpeg | 2.1.0.1 | 2014-04-08 01:06:14Z |  |
## System Info

```
OS: 
    Type: Windows
    VersionNumber: 6.3.9600.0
    VersionString: Microsoft Windows NT 6.3.9600.0
    Is64Bit: True
Hardware: 
    ProcessorCount: 4
    TotalPhysicalMemory: 4186292224 bytes (3,9 GiB)
    AvailableMemory: 309747712 bytes (295,4 MiB)
Process: 
    MemoryWidth: 64
    Is64Bit: True
Culture: 
    InstalledUICulture: da-DK
    CurrentCulture: da-DK
    CurrentUICulture: da-DK
```

**Comment by bdhero-issues** [comment] 2014-04-14 09:46
BDHero GUI v0.9.0.6 (built on 2014-04-08 01:06:16Z)

## Stack Trace

```
System.IndexOutOfRangeException: Indekset lå uden for arrayets grænser.
   ved BDInfo.TSStreamFile.Scan(List`1 playlists, Boolean isFullScan)
   ved BDInfo.BDROM.Scan(CancellationToken cancellationToken)
   ved BDHero.Plugin.DiscReader.DiscReader.ScanBDROM(CancellationToken cancellationToken, String bdromPath)
   ved BDHero.Plugin.DiscReader.DiscReader.ReadBDROM(CancellationToken cancellationToken, String bdromPath)
   ved BDHero.Controller.<>c__DisplayClass29.<ReadBDROM>b__27(CancellationToken token)
   ved BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   ved DotNetUtils.Concurrency.Promise`1.Work()
   ved DotNetUtils.Concurrency.Promise`1.TryDoWork()

Source: BDInfo
```

## Log Events

```
2014-04-14 11:47:18,499 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:20 elapsed, 00:00:01 remaining
2014-04-14 11:47:18,747 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:20 elapsed, 00:00:01 remaining
2014-04-14 11:47:19,016 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:20 elapsed, 00:00:01 remaining
2014-04-14 11:47:19,263 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:21 elapsed, 00:00:01 remaining
2014-04-14 11:47:19,513 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:21 elapsed, 00:00:01 remaining
2014-04-14 11:47:19,766 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:21 elapsed, 00:00:01 remaining
2014-04-14 11:47:20,027 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:21 elapsed, 00:00:01 remaining
2014-04-14 11:47:20,293 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:22 elapsed, 00:00:01 remaining
2014-04-14 11:47:20,544 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:22 elapsed, 00:00:01 remaining
2014-04-14 11:47:20,799 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:22 elapsed, 00:00:01 remaining
2014-04-14 11:47:21,047 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:22 elapsed, 00:00:01 remaining
2014-04-14 11:47:21,298 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:23 elapsed, 00:00:01 remaining
2014-04-14 11:47:21,560 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:23 elapsed, 00:00:01 remaining
2014-04-14 11:47:21,811 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:23 elapsed, 00:00:01 remaining
2014-04-14 11:47:22,076 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:23 elapsed, 00:00:01 remaining
2014-04-14 11:47:22,346 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:24 elapsed, 00:00:01 remaining
2014-04-14 11:47:22,599 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:24 elapsed, 00:00:01 remaining
2014-04-14 11:47:22,862 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:24 elapsed, 00:00:01 remaining
2014-04-14 11:47:23,120 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:25 elapsed, 00:00:01 remaining
2014-04-14 11:47:23,378 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:25 elapsed, 00:00:01 remaining
2014-04-14 11:47:23,621 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:25 elapsed, 00:00:01 remaining
2014-04-14 11:47:23,871 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:25 elapsed, 00:00:01 remaining
2014-04-14 11:47:24,137 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:26 elapsed, 00:00:01 remaining
2014-04-14 11:47:24,401 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:26 elapsed, 00:00:01 remaining
2014-04-14 11:47:24,654 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:26 elapsed, 00:00:01 remaining
2014-04-14 11:47:24,906 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:26 elapsed, 00:00:01 remaining
2014-04-14 11:47:25,166 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:27 elapsed, 00:00:01 remaining
2014-04-14 11:47:25,418 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:27 elapsed, 00:00:01 remaining
2014-04-14 11:47:25,684 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:27 elapsed, 00:00:01 remaining
2014-04-14 11:47:25,951 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:27 elapsed, 00:00:01 remaining
2014-04-14 11:47:26,202 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:28 elapsed, 00:00:01 remaining
2014-04-14 11:47:26,450 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:28 elapsed, 00:00:01 remaining
2014-04-14 11:47:26,713 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:28 elapsed, 00:00:01 remaining
2014-04-14 11:47:26,964 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:28 elapsed, 00:00:01 remaining
2014-04-14 11:47:27,224 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:29 elapsed, 00:00:01 remaining
2014-04-14 11:47:27,467 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:29 elapsed, 00:00:01 remaining
2014-04-14 11:47:27,730 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:29 elapsed, 00:00:01 remaining
2014-04-14 11:47:27,980 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:29 elapsed, 00:00:01 remaining
2014-04-14 11:47:28,245 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:30 elapsed, 00:00:01 remaining
2014-04-14 11:47:28,496 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:30 elapsed, 00:00:01 remaining
2014-04-14 11:47:28,766 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:30 elapsed, 00:00:01 remaining
2014-04-14 11:47:29,011 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:30 elapsed, 00:00:01 remaining
2014-04-14 11:47:29,279 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:31 elapsed, 00:00:02 remaining
2014-04-14 11:47:29,527 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:31 elapsed, 00:00:02 remaining
2014-04-14 11:47:29,778 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:31 elapsed, 00:00:02 remaining
2014-04-14 11:47:30,028 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:31 elapsed, 00:00:02 remaining
2014-04-14 11:47:30,279 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:32 elapsed, 00:00:02 remaining
2014-04-14 11:47:30,550 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:32 elapsed, 00:00:02 remaining
2014-04-14 11:47:30,718 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Error - 93,97 % complete - Scanning stream file 00017.M2TS - 00:00:32 elapsed, 00:00:02 remaining
2014-04-14 11:47:30,723 [ 1] ERROR BDHero.Controller - Unhandled exception was thrown by plugin
```

## Plugins

| R/O | Plugin Name | Version | Build Date | E/D |
| --- | --- | --- | --- | --- |
| 0 | BDInfo Disc Reader | 0.5.8.2 | 2014-04-08 01:06:11Z |  |
| 0 | ISAN Metadata Provider | 0.9.0.6 | 2014-04-08 01:06:11Z |  |
| 1 | TMDb | 0.9.0.6 | 2014-04-08 01:06:11Z |  |
| 2 | ChapterDb | 0.9.0.6 | 2014-04-08 01:06:11Z |  |
| 0 | BDHero Detective | 0.9.0.6 | 2014-04-08 01:06:11Z |  |
| 0 | BDHero File Namer | 0.9.0.6 | 2014-04-08 01:06:12Z |  |
| 0 | FFmpeg | 2.1.0.1 | 2014-04-08 01:06:14Z |  |

## System Info

```
OS: 
    Type: Windows
    VersionNumber: 6.3.9600.0
    VersionString: Microsoft Windows NT 6.3.9600.0
    Is64Bit: True
Hardware: 
    ProcessorCount: 4
    TotalPhysicalMemory: 4186292224 bytes (3,9 GiB)
    AvailableMemory: 167129088 bytes (159,4 MiB)
Process: 
    MemoryWidth: 64
    Is64Bit: True
Culture: 
    InstalledUICulture: da-DK
    CurrentCulture: da-DK
    CurrentUICulture: da-DK
```

**Comment by acdvorak** [comment] 2014-04-14 22:04
Duplicate of #24

**Comment by acdvorak** [comment] 2014-04-15 05:42
Need more info to investigate.  Added more detailed logging output in v0.9.0.7.

**Closed as completed by acdvorak** 2014-04-15 05:42 UTC
Labels: duplicate, report, need-more-info
