### ISSUE TITLE
BDHero GUI v0.9.0.6: System.IndexOutOfRangeException: De index ligt buiten de matrixgrenzen.

### ISSUE THREAD

**Issue by bdhero-issues** [bdhero/bdhero#25] opened 2014-04-12 21:54 UTC
BDHero GUI v0.9.0.6 (built on 2014-04-08 01:06:16Z)
## Stack Trace

```
System.IndexOutOfRangeException: De index ligt buiten de matrixgrenzen.
   bij BDInfo.TSStreamFile.Scan(List`1 playlists, Boolean isFullScan)
   bij BDInfo.BDROM.Scan(CancellationToken cancellationToken)
   bij BDHero.Plugin.DiscReader.DiscReader.ScanBDROM(CancellationToken cancellationToken, String bdromPath)
   bij BDHero.Plugin.DiscReader.DiscReader.ReadBDROM(CancellationToken cancellationToken, String bdromPath)
   bij BDHero.Controller.<>c__DisplayClass29.<ReadBDROM>b__27(CancellationToken token)
   bij BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   bij DotNetUtils.Concurrency.Promise`1.Work()
   bij DotNetUtils.Concurrency.Promise`1.TryDoWork()

Source: BDInfo
```
## Log Events

```
2014-04-12 23:53:34,579 [ 1] DEBUG BDHeroGUI.Components.DiscMenu - Found 1 discs
2014-04-12 23:53:37,954 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 0.00 % complete -  - 00:00:00 elapsed, 00:00:00 remaining
2014-04-12 23:53:38,204 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 0.00 % complete - Scanning BD-ROM... - 00:00:00 elapsed, 00:00:00 remaining
2014-04-12 23:53:39,157 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 0.00 % complete - Scanning stream clip file 00002.CLPI - 00:00:01 elapsed, 00:00:00 remaining
2014-04-12 23:53:39,251 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 35.77 % complete - Scanning stream clip file 00090.CLPI - 00:00:01 elapsed, 00:00:02 remaining
2014-04-12 23:53:39,360 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 63.23 % complete - Scanning stream file 00018.M2TS - 00:00:01 elapsed, 00:00:02 remaining
2014-04-12 23:53:39,501 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 74.87 % complete - Scanning stream file 00089.M2TS - 00:00:01 elapsed, 00:00:02 remaining
2014-04-12 23:53:39,704 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 79.03 % complete - Scanning stream file 00002.M2TS - 00:00:01 elapsed, 00:00:00 remaining
2014-04-12 23:53:39,954 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 85.69 % complete - Scanning stream file 00057.M2TS - 00:00:01 elapsed, 00:00:00 remaining
2014-04-12 23:53:40,282 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 85.69 % complete - Scanning stream file 00057.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-04-12 23:53:40,548 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 85.69 % complete - Scanning stream file 00057.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-04-12 23:53:40,798 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 85.69 % complete - Scanning stream file 00057.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-04-12 23:53:41,048 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 85.69 % complete - Scanning stream file 00057.M2TS - 00:00:03 elapsed, 00:00:00 remaining
2014-04-12 23:53:41,188 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 86.52 % complete - Scanning stream file 00057.M2TS - 00:00:03 elapsed, 00:00:00 remaining
2014-04-12 23:53:41,313 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 86.52 % complete - Scanning stream file 00087.M2TS - 00:00:03 elapsed, 00:00:00 remaining
2014-04-12 23:53:41,563 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 86.52 % complete - Scanning stream file 00087.M2TS - 00:00:03 elapsed, 00:00:00 remaining
2014-04-12 23:53:41,829 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 86.52 % complete - Scanning stream file 00087.M2TS - 00:00:03 elapsed, 00:00:00 remaining
2014-04-12 23:53:42,095 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 86.52 % complete - Scanning stream file 00087.M2TS - 00:00:04 elapsed, 00:00:00 remaining
2014-04-12 23:53:42,360 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 86.52 % complete - Scanning stream file 00087.M2TS - 00:00:04 elapsed, 00:00:00 remaining
2014-04-12 23:53:42,626 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 87.35 % complete - Scanning stream file 00055.M2TS - 00:00:04 elapsed, 00:00:00 remaining
2014-04-12 23:53:42,876 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 87.35 % complete - Scanning stream file 00055.M2TS - 00:00:04 elapsed, 00:00:00 remaining
2014-04-12 23:53:43,126 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 87.35 % complete - Scanning stream file 00055.M2TS - 00:00:05 elapsed, 00:00:00 remaining
2014-04-12 23:53:43,313 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Error - 87.35 % complete - Scanning stream file 00055.M2TS - 00:00:05 elapsed, 00:00:00 remaining
2014-04-12 23:53:43,313 [ 1] ERROR BDHero.Controller - Unhandled exception was thrown by plugin
System.IndexOutOfRangeException: De index ligt buiten de matrixgrenzen.
   bij BDInfo.TSStreamFile.Scan(List`1 playlists, Boolean isFullScan)
   bij BDInfo.BDROM.Scan(CancellationToken cancellationToken)
   bij BDHero.Plugin.DiscReader.DiscReader.ScanBDROM(CancellationToken cancellationToken, String bdromPath)
   bij BDHero.Plugin.DiscReader.DiscReader.ReadBDROM(CancellationToken cancellationToken, String bdromPath)
   bij BDHero.Controller.<>c__DisplayClass29.<ReadBDROM>b__27(CancellationToken token)
   bij BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   bij DotNetUtils.Concurrency.Promise`1.Work()
   bij DotNetUtils.Concurrency.Promise`1.TryDoWork()
2014-04-12 23:54:00,611 [ 1] DEBUG BDHeroGUI.FormMain - Scan failed!
2014-04-12 23:54:21,972 [ 1] DEBUG BDHeroGUI.Components.DiscMenu - Scanning for discs...
2014-04-12 23:54:22,096 [ 1] DEBUG BDHeroGUI.Components.DiscMenu - Found 1 discs
2014-04-12 23:54:35,003 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 0.00 % complete - Scanning stream file 00055.M2TS - 00:00:00 elapsed, 00:00:00 remaining
2014-04-12 23:54:35,253 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 0.00 % complete - Scanning BD-ROM... - 00:00:00 elapsed, 00:00:00 remaining
2014-04-12 23:54:35,878 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 45.76 % complete - Scanning playlist file 00032.MPLS - 00:00:00 elapsed, 00:00:00 remaining
2014-04-12 23:54:35,988 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 73.21 % complete - Scanning stream file 00068.M2TS - 00:00:00 elapsed, 00:00:00 remaining
2014-04-12 23:54:36,128 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 78.20 % complete - Scanning stream file 00002.M2TS - 00:00:01 elapsed, 00:00:00 remaining
2014-04-12 23:54:36,284 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 81.53 % complete - Scanning stream file 00020.M2TS - 00:00:01 elapsed, 00:00:00 remaining
2014-04-12 23:54:36,503 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 83.19 % complete - Scanning stream file 00058.M2TS - 00:00:01 elapsed, 00:00:00 remaining
2014-04-12 23:54:36,784 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 85.69 % complete - Scanning stream file 00057.M2TS - 00:00:01 elapsed, 00:00:00 remaining
2014-04-12 23:54:37,035 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 85.69 % complete - Scanning stream file 00057.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-04-12 23:54:37,300 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 85.69 % complete - Scanning stream file 00057.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-04-12 23:54:37,550 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 85.69 % complete - Scanning stream file 00057.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-04-12 23:54:37,706 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 86.52 % complete - Scanning stream file 00057.M2TS - 00:00:02 elapsed, 00:00:00 remaining
2014-04-12 23:54:38,066 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 86.52 % complete - Scanning stream file 00087.M2TS - 00:00:03 elapsed, 00:00:00 remaining
2014-04-12 23:54:38,331 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 86.52 % complete - Scanning stream file 00087.M2TS - 00:00:03 elapsed, 00:00:00 remaining
2014-04-12 23:54:38,581 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 86.52 % complete - Scanning stream file 00087.M2TS - 00:00:03 elapsed, 00:00:00 remaining
2014-04-12 23:54:38,831 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 86.52 % complete - Scanning stream file 00087.M2TS - 00:00:03 elapsed, 00:00:00 remaining
2014-04-12 23:54:38,988 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 87.35 % complete - Scanning stream file 00087.M2TS - 00:00:03 elapsed, 00:00:00 remaining
2014-04-12 23:54:39,113 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 87.35 % complete - Scanning stream file 00055.M2TS - 00:00:04 elapsed, 00:00:00 remaining
2014-04-12 23:54:39,347 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 87.35 % complete - Scanning stream file 00055.M2TS - 00:00:04 elapsed, 00:00:00 remaining
2014-04-12 23:54:39,597 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 87.35 % complete - Scanning stream file 00055.M2TS - 00:00:04 elapsed, 00:00:00 remaining
2014-04-12 23:54:39,847 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Running - 87.35 % complete - Scanning stream file 00055.M2TS - 00:00:04 elapsed, 00:00:00 remaining
2014-04-12 23:54:39,925 [ 1] DEBUG BDHeroGUI.FormMain - BDInfo Disc Reader is Error - 87.35 % complete - Scanning stream file 00055.M2TS - 00:00:04 elapsed, 00:00:00 remaining
2014-04-12 23:54:39,925 [ 1] ERROR BDHero.Controller - Unhandled exception was thrown by plugin
```
## Plugins

| R/O | Plugin Name | Version | Build Date | E/D |
| --- | --- | --- | --- | --- |
| 0 | BDInfo Disc Reader | 0.5.8.2 | 2014-04-08 01:06:11Z |  |
| 0 | ISAN Metadata Provider | 0.9.0.6 | 2014-04-08 01:06:11Z |  |
| 1 | TMDb | 0.9.0.6 | 2014-04-08 01:06:11Z |  |
| 2 | ChapterDb | 0.9.0.6 | 2014-04-08 01:06:11Z |  |
| 0 | BDHero Detective | 0.9.0.6 | 2014-04-08 01:06:11Z |  |
| 0 | BDHero File Namer | 0.9.0.6 | 2014-04-08 01:06:12Z |  |
| 0 | FFmpeg | 2.1.0.1 | 2014-04-08 01:06:14Z |  |
## System Info

```
OS: 
    Type: Windows
    VersionNumber: 6.3.9600.0
    VersionString: Microsoft Windows NT 6.3.9600.0
    Is64Bit: True
Hardware: 
    ProcessorCount: 8
    TotalPhysicalMemory: 17122549760 bytes (15.9 GiB)
    AvailableMemory: 14719455232 bytes (13.7 GiB)
Process: 
    MemoryWidth: 64
    Is64Bit: True
Culture: 
    InstalledUICulture: nl-NL
    CurrentCulture: nl-NL
    CurrentUICulture: nl-NL
```

**Comment by acdvorak** [comment] 2014-04-14 22:04
Duplicate of #24

**Comment by acdvorak** [comment] 2014-04-15 05:42
Need more info to investigate.  Added more detailed logging output in v0.9.0.7.

**Closed as completed by acdvorak** 2014-04-15 05:42 UTC
Labels: duplicate, report, need-more-info
