### ISSUE TITLE
BDHero GUI v0.9.0.9: BDHero.Plugin.FFmpegMuxer.FFmpegException: [mpegts @ 027ae600] max resync size reached, could not find sync byte

### ISSUE THREAD

**Issue by bdhero-issues** [bdhero/bdhero#34] opened 2014-04-19 12:25 UTC
BDHero GUI v0.9.0.9 (built on 2014-04-18 10:56:23Z)
## Stack Trace

```
BDHero.Plugin.FFmpegMuxer.FFmpegException: [mpegts @ 027ae600] max resync size reached, could not find sync byte ---> BDHero.Plugin.FFmpegMuxer.FFmpegException: [mpegts @ 027ae600] max resync size reached, could not find sync byte
   at BDHero.Plugin.FFmpegMuxer.FFmpeg.OnStdErr(String line) in [redacted]\FFmpeg.cs:line 457
   --- End of inner exception stack trace ---
   at BDHero.Plugin.FFmpegMuxer.FFmpegPlugin.Mux(CancellationToken cancellationToken, Job job) in [redacted]\FFmpegPlugin.cs:line 108
   at BDHero.Controller.<>c__DisplayClass42.<Mux>b__41(CancellationToken token)
   at BDHero.Controller.<>c__DisplayClass24.<RunPluginSync>b__22(IPromise`1 param0)
   at DotNetUtils.Concurrency.Promise`1.Work()
   at DotNetUtils.Concurrency.Promise`1.TryDoWork()

Source: FFmpegMuxerPlugin
```
## Log Events

```
2014-04-19 22:15:49,924 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:20 elapsed, 02:43:12 remaining
2014-04-19 22:15:50,179 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:20 elapsed, 02:43:12 remaining
2014-04-19 22:15:50,443 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:21 elapsed, 02:43:11 remaining
2014-04-19 22:15:50,707 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:21 elapsed, 02:43:32 remaining
2014-04-19 22:15:50,767 [ 1] DEBUG ProcessUtils.BackgroundProcessWorker - Timer tick
2014-04-19 22:15:50,960 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:21 elapsed, 02:43:32 remaining
2014-04-19 22:15:51,219 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:21 elapsed, 02:43:32 remaining
2014-04-19 22:15:51,489 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:22 elapsed, 02:43:32 remaining
2014-04-19 22:15:51,737 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:22 elapsed, 02:43:31 remaining
2014-04-19 22:15:51,782 [ 1] DEBUG ProcessUtils.BackgroundProcessWorker - Timer tick
2014-04-19 22:15:51,999 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:22 elapsed, 02:43:31 remaining
2014-04-19 22:15:52,265 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:23 elapsed, 02:43:31 remaining
2014-04-19 22:15:52,519 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:23 elapsed, 02:43:31 remaining
2014-04-19 22:15:52,781 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:23 elapsed, 02:43:30 remaining
2014-04-19 22:15:52,795 [ 1] DEBUG ProcessUtils.BackgroundProcessWorker - Timer tick
2014-04-19 22:15:53,045 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:23 elapsed, 02:43:30 remaining
2014-04-19 22:15:53,295 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:24 elapsed, 02:43:30 remaining
2014-04-19 22:15:53,560 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:24 elapsed, 02:43:30 remaining
2014-04-19 22:15:53,808 [ 1] DEBUG ProcessUtils.BackgroundProcessWorker - Timer tick
2014-04-19 22:15:54,076 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:24 elapsed, 02:43:29 remaining
2014-04-19 22:15:54,340 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:25 elapsed, 02:43:29 remaining
2014-04-19 22:15:54,609 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:25 elapsed, 02:43:28 remaining
2014-04-19 22:15:54,822 [ 1] DEBUG ProcessUtils.BackgroundProcessWorker - Timer tick
2014-04-19 22:15:55,120 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:25 elapsed, 02:43:28 remaining
2014-04-19 22:15:55,388 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:26 elapsed, 02:43:49 remaining
2014-04-19 22:15:55,639 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:26 elapsed, 02:43:49 remaining
2014-04-19 22:15:55,836 [ 1] DEBUG ProcessUtils.BackgroundProcessWorker - Timer tick
2014-04-19 22:15:56,166 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:26 elapsed, 02:43:48 remaining
2014-04-19 22:15:56,417 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:27 elapsed, 02:43:48 remaining
2014-04-19 22:15:56,679 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:27 elapsed, 02:43:48 remaining
2014-04-19 22:15:56,850 [ 1] DEBUG ProcessUtils.BackgroundProcessWorker - Timer tick
2014-04-19 22:15:57,196 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:27 elapsed, 02:43:47 remaining
2014-04-19 22:15:57,665 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:28 elapsed, 02:43:47 remaining
2014-04-19 22:15:57,725 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 22.09 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 10.0 fps - 00:46:28 elapsed, 02:43:47 remaining
2014-04-19 22:15:57,864 [ 1] DEBUG ProcessUtils.BackgroundProcessWorker - Timer tick
2014-04-19 22:15:57,865 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 100.00 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 9.9 fps - 00:46:28 elapsed, 02:43:47 remaining
2014-04-19 22:15:57,980 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Running - 100.00 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 9.9 fps - 00:46:28 elapsed, 00:00:00 remaining
2014-04-19 22:15:58,043 [17] INFO  ProcessUtils.NonInteractiveProcess - Process "[redacted].exe" exited (asynchronous event)
2014-04-19 22:15:58,043 [15] INFO  ProcessUtils.NonInteractiveProcess - Process "[redacted].exe" w/ PID = 14168 exited
2014-04-19 22:15:58,487 [15] INFO  ProcessUtils.NonInteractiveProcess - Process "[redacted].exe" exited (synchronous event)
2014-04-19 22:15:58,508 [15] INFO  ProcessUtils.NonInteractiveProcess - Process "[redacted].exe" changing state from Running to Error
2014-04-19 22:15:58,910 [15] ERROR BDHero.Plugin.FFmpegMuxer.FFmpeg - FFmpeg exited with state Error and code 0
2014-04-19 22:15:59,137 [15] INFO  BDHero.Plugin.FFmpegMuxer.FFmpegPlugin - FFmpeg exited with state Error and code 0
2014-04-19 22:15:59,257 [13] INFO  BDHero.Plugin.FFmpegMuxer.FFmpegPlugin - FFmpeg was invoked with: "[redacted].exe" -report -loglevel error -progress [redacted].log -y -f concat -i [redacted].txt -metadata "title=Fantastic Mr. Fox (2009)" -map 0:0 -metadata:s:0 language=eng -metadata:s:0 "title=Main Feature: H.264 (1080p)" -map 0:1 -metadata:s:1 language=eng -metadata:s:1 "title=Main Feature: DTS-HD MA (5.1 ch)" -map 0:2 -metadata:s:2 language=eng -metadata:s:2 "title=Main Feature: PGS" -c copy "[redacted].mkv"
2014-04-19 22:15:59,277 [13] INFO  BDHero.Plugin.FFmpegMuxer.FFmpegPlugin - Release medium: Movie { Id = 10315 }: Fantastic Mr. Fox (2009)
2014-04-19 22:15:59,307 [13] INFO  BDHero.Plugin.FFmpegMuxer.FFmpeg - Tracks:
    Track w/ stream PID 4113 (0x1011): index  0 =>  0 [X] (eng, V_MPEG4/ISO/AVC - H.264/MPEG-4 AVC (MPEG-4 Part 10))
    Track w/ stream PID 4352 (0x1100): index  1 =>  1 [X] (eng, A_DTS - DTS-HD Master Audio)
    Track w/ stream PID 4608 (0x1200): index  2 =>  2 [X] (eng, S_HDMV/PGS - Presentation Graphics Stream)
2014-04-19 22:15:59,336 [13] WARN  BDHero.Plugin.FFmpegMuxer.FFmpeg - StdErr:
    2014-04-19 21:29:30,562 [mpegts @ 027ae600] max resync size reached, could not find sync byte
    2014-04-19 22:15:15,246     Last message repeated 260582 times
2014-04-19 22:15:59,429 [13] WARN  BDHero.Plugin.FFmpegMuxer.FFmpeg - Report Dump:
    [matroska @ 058cfa40] Writing block at offset 4629211574, size 5532, pts 1149333, dts 1149333, duration 11, flags 128
    [matroska @ 058cfa40] Writing block at offset 4629217113, size 5528, pts 1149343, dts 1149343, duration 11, flags 128
    [matroska @ 058cfa40] Writing block at offset 4629222648, size 5424, pts 1149354, dts 1149354, duration 11, flags 128
    [matroska @ 058cfa40] Writing block at offset 4629228079, size 75699, pts 1149440, dts 1149357, duration 42, flags 0
    [matroska @ 058cfa40] Writing block at offset 4629303786, size 5284, pts 1149365, dts 1149365, duration 11, flags 128
    [matroska @ 058cfa40] Writing block at offset 4629309077, size 5164, pts 1149375, dts 1149375, duration 11, flags 128
    [matroska @ 058cfa40] Writing block at offset 4629314248, size 5056, pts 1149386, dts 1149386, duration 11, flags 128
    [matroska @ 058cfa40] Writing block at offset 4629319311, size 4952, pts 1149397, dts 1149397, duration 11, flags 128
    [matroska @ 058cfa40] Writing block at offset 4629324270, size 19962, pts 1149399, dts 1149399, duration 42, flags 0
    [matroska @ 058cfa40] Writing block at offset 4629344240, size 4876, pts 1149407, dts 1149407, duration 11, flags 128
    [matroska @ 058cfa40] Writing block at offset 4629349123, size 4780, pts 1149418, dts 1149418, duration 11, flags 128
    [matroska @ 058cfa40] Writing block at offset 4629353910, size 4724, pts 1149429, dts 1149429, duration 11, flags 128
    [matroska @ 058cfa40] Starting new cluster at offset 4629358641 bytes, pts 1149482dts 1149440
    [matroska @ 058cfa40] Writing block at offset 4629358658, size 4708, pts 1149439, dts 1149439, duration 11, flags 128
    [matroska @ 058cfa40] Writing block at offset 4629363373, size 582168, pts 1149482, dts 1149440, duration 42, flags 128
    [matroska @ 058cfa40] Writing block at offset 4629945549, size 4672, pts 1149450, dts 1149450, duration 11, flags 128
    [matroska @ 058cfa40] Writing block at offset 4629950228, size 4692, pts 1149461, dts 1149461, duration 11, flags 128
    [matroska @ 058cfa40] Writing block at offset 4629954927, size 5082, pts 1149471, dts 1149471, duration 11, flags 128
    [matroska @ 058cfa40] Writing block at offset 4629960016, size 216549, pts 1149649, dts 1149482, duration 42, flags 0
    [matroska @ 058cfa40] Starting new cluster at offset 4630176576 bytes, pts 1149482dts 1149482
    [matroska @ 058cfa40] Writing block at offset 4630176593, size 1821, pts 1149482, dts 1149482, duration 42, flags 128
    [matroska @ 058cfa40] end duration = 1150191
    frame=27562 fps=9.9 q=-1.0 Lsize= 4521744kB time=00:19:09.44 bitrate=32226.2kbits/s
    [AVIOContext @ 02660be0] Statistics: 0 seeks, 4793 writeouts
    video:4074928kB audio:437986kB subtitle:7740 data:0 global headers:0kB muxing overhead 0.024114%
    0 frames successfully decoded, 0 decoding errors
    [AVIOContext @ 057eb3a0] Statistics: 16730 seeks, 239016 writeouts
    [AVIOContext @ 02661800] Statistics: 21958580592 bytes read, 6 seeks
    [AVIOContext @ 02661320] Statistics: 99 bytes read, 0 seeks
2014-04-19 22:15:59,782 [ 1] DEBUG BDHeroGUI.FormMain - FFmpeg is Error - 100.00 % complete - Muxing to MKV: 00:19:09.440 - 4.3 GiB @ 9.9 fps - 00:46:30 elapsed, 00:00:00 remaining
2014-04-19 22:15:59,807 [ 1] ERROR BDHero.Controller - Unhandled exception was thrown by plugin
```
## Plugins

| R/O | Plugin Name | Version | Build Date | E/D |
| --- | --- | --- | --- | --- |
| 0 | BDInfo Disc Reader | 0.5.8.2 | 2014-04-18 10:56:19Z |  |
| 0 | ISAN Metadata Provider | 0.9.0.9 | 2014-04-18 10:56:18Z |  |
| 1 | TMDb | 0.9.0.9 | 2014-04-18 10:56:18Z |  |
| 2 | ChapterDb | 0.9.0.9 | 2014-04-18 10:56:18Z |  |
| 0 | BDHero Detective | 0.9.0.9 | 2014-04-18 10:56:18Z |  |
| 0 | BDHero File Namer | 0.9.0.9 | 2014-04-18 10:56:17Z |  |
| 0 | FFmpeg | 2.2.1.0 | 2014-04-18 10:56:18Z |  |
## System Info

```
OS: 
    Type: Windows
    VersionNumber: 6.1.7601.65536
    VersionString: Microsoft Windows NT 6.1.7601 Service Pack 1
    Is64Bit: True
Hardware: 
    ProcessorCount: 8
    TotalPhysicalMemory: 4215828480 bytes (3.9 GiB)
    AvailableMemory: 2275663872 bytes (2.1 GiB)
Process: 
    MemoryWidth: 64
    Is64Bit: True
Culture: 
    InstalledUICulture: en-US
    CurrentCulture: en-AU
    CurrentUICulture: en-US
```

**Comment by acdvorak** [comment] 2014-04-19 14:53
Duplicate of #32

**Closed as completed by acdvorak** 2014-04-19 14:53 UTC
Labels: report
